### ISSUE TITLE
Shortcut notation for assigning classes ignored

### ISSUE THREAD

**Issue by fishb6nes** [lukasjapan/koreander#3]
Heya Lukas,

Love the syntax, but I've ran into an issue with the shortcut notation for assigning classes.

According to the readme it should be possible to use `%tag.myclass → <tag class="myclass"></tag>`.
However, when parsing `%span.test test span with test class` the result is 
`<span.test>test span with test class</span.test>` instead.

Would be awesome if you could try to replicate,
Many thanks in advance and a fantastic holiday season,
fish

template.kor:
```
!!! 5
%html
  %head
    %title Test title

  %body
    .test
      %p test div with test class
      %span.test test span with test class
```
app.kt:
```
data class Model(val name: String = "")

class app {
    fun generateHtml(): String {
        val viewUrl = javaClass.getResource("template.kor")
        return Koreander().render(viewUrl, Model())
    }
}
```

**Comment by lukasjapan** [comment]
Thanks for reporting this bug. Very much appreciated!

It is now fixed and I confirmed it is working with an additional testcase.

Will separately confirm with a real project later today.

Happy holidays!
